import distutils.util
import os
pj = os.path.join

Import('GetPlatform', 'optimize')

builddir = "build." + distutils.util.get_platform()
if optimize != 'no':
   builddir = builddir + '.opt'
BuildDir(builddir, 'TestSuite', duplicate=0)

SConscript(dirs = builddir)
